Develop
genomehubs/goat-ui pull request #77
Opened 2024-06-03 22:46 UTC by ccaio

2024-06-04 08:23 UTC, rjchallis requested changes
Mostly looking good, just a few details about link naming and tab syntax - I've pushed a new release of genomehubs to let you use `_` in a filename to get a ` ` in the rendered tab name and to break out of the nested path by prefixing with `/` instead of using `+...+` as that is causing the browser to look for a files that do not exist. (you should still use `+...+` in `tabs.md`, just not in `tabs-*.md`)

2024-06-04 08:23 UTC, rjchallis commented on static/tabs-search.md
attempts to link to `/browser` because of the `+...+` but the file has moved to `/search/browser`

2024-06-04 08:23 UTC, rjchallis commented on static/tabs-help.md
links to `/search/wiki` but the file is at `/wiki`

using `+...+` to link back up to the top level is working for nested tabs but was not designed like that. It is causing the browser to request a `/tabs-help-about.md` file that does not exists so the console has 404 errors. 

I've pushed a new release that lets you link back to the top level from a nested tab group by prefixing with  `/`, e.g.:
```
- /about
- /api
- uses
...
``` 

`uses` should be `use_cases`

2024-06-04 08:23 UTC, rjchallis commented on static/wiki.md
Title not formatted as markdown title

2024-06-04 08:23 UTC, rjchallis commented on static/search/browser.md
moving this breaks the breadcrumb links for `/browser/chiroptera`, etc

2024-06-04 08:23 UTC, rjchallis commented on static/projects/all-projects.md
prefer `_` for a space that should be shown as ` `

2024-06-04 08:23 UTC, rjchallis commented on static/tabs-projects.md
I've pushed a new genomehubs release that will render `all_projects` as `all projects`, but leave `EBP-affiliates` as `EBP-affiliates` if you use `_` for a space that should be shown as ` ` in file/tab names.

2024-06-04 08:23 UTC, rjchallis commented on static/help/uses.md
should be `use_cases.md` to match content

2024-06-08 02:07 UTC, ccaio commented on static/tabs-projects.md
moved project sessions to static/projects and kept /regions as direct link

2024-06-08 02:10 UTC, ccaio commented on static/tabs-search.md
Moved browser back to /browser, but not sure if that's the right decision for this one.

2024-06-10 10:38 UTC, rjchallis approved these changes

2024-06-10 10:38 UTC, rjchallis commented on static/projects.md
could use `.inline` instead of `.paragraph` here to avoid indenting the included pages, but fine as is

2024-06-10 10:38 UTC, rjchallis commented on static/tabs-search.md
I think that's fine

2024-06-11 23:01 UTC, merged